metricbeat.config.modules:
  path: conf/*.yml
  reload.enabled: true

output.logstash:
  hosts: ${BLUECATS_HOST:?환경변수 값으로 BLUECATS_HOST값을 127.0.0.1:7700 과 같은 형태로 추가하세요.}

processors:
- add_locale: ~
- add_host_metadata: 
    netinfo.enabled: true  
- add_fields:
    target: beat
    fields:
      version: VERSION_INFO_HERE    
- add_tags:
    tags: ${BLUECATS_SITE:?환경변수 값으로 BLUECATS_SITE을 S1 혹은 16L 과 같은 형태로 추가하세요.}
- add_fields:
    target: mirero
    fields:
      kafka_topic: metricbeat    # dms 5.0 전용
      dms50: ${BLUECATS_DMS50:false}
- add_tags:
    tags: [dms, dms50]
    when: 
      equals:
        mirero.dms50: true      
